# Generated by Django 3.2.9 on 2021-12-02 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('sex', models.CharField(max_length=1)),
                ('VO2_max', models.FloatField(null=True)),
                ('rhr', models.IntegerField()),
                ('fluid_loss', models.FloatField(null=True)),
                ('sodium_loss', models.FloatField(null=True)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('is_athlete', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('incomplete', models.URLField()),
                ('complete', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=14)),
                ('max_participants', models.IntegerField()),
                ('course_url', models.URLField()),
                ('event_logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=50)),
                ('is_athlete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('elev_gain', models.FloatField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticapi.event')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticapi.sport')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticapi.organizer'),
        ),
        migrations.CreateModel(
            name='AthleteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticapi.athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticapi.event')),
            ],
        ),
        migrations.CreateModel(
            name='AthleteBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_on', models.DateField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticapi.athlete')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticapi.badge')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateField()),
                ('distance', models.FloatField()),
                ('elev_gain', models.FloatField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticapi.activity')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticapi.sport')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticapi.athlete'),
        ),
    ]
