# Generated by Django 3.2.9 on 2021-12-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kineticapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_sports',
            field=models.ManyToManyField(related_name='sports', through='kineticapi.EventSport', to='kineticapi.Sport'),
        ),
    ]
