# Generated by Django 3.2.9 on 2021-12-06 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kineticapi', '0002_auto_20211205_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_sport',
        ),
        migrations.AlterField(
            model_name='eventsport',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sports', to='kineticapi.event'),
        ),
    ]
