# Generated by Django 3.2.9 on 2021-12-03 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kineticapi', '0002_event_event_sports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_sports',
        ),
        migrations.AddField(
            model_name='event',
            name='sports',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event_sports', to='kineticapi.eventsport'),
        ),
        migrations.AlterField(
            model_name='eventsport',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sport', to='kineticapi.event'),
        ),
    ]
