# Generated by Django 3.2.10 on 2021-12-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kineticapi', '0003_auto_20211206_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysport',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='activitysport',
            name='name',
        ),
    ]
