# Generated by Django 3.2.10 on 2021-12-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kineticapi', '0004_auto_20211215_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteevent',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
