# Generated by Django 3.2.9 on 2021-12-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kineticapi', '0005_alter_event_sports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sports',
        ),
    ]
