# Generated by Django 3.2.10 on 2022-01-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kineticapi', '0005_auto_20211221_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='complete',
            new_name='complete_url',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='incomplete',
            new_name='incomplete_url',
        ),
        migrations.AddField(
            model_name='badge',
            name='description',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
