# Generated by Django 3.2.10 on 2022-01-04 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kineticapi', '0006_auto_20220104_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletebadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_badge', to='kineticapi.badge'),
        ),
    ]
